### ISSUE TITLE
_lumigo folder is not included when packaging individually

### ISSUE THREAD

**Issue by theburningmonk** [lumigo-io/serverless-lumigo-plugin#10]
e.g. given the following `serverless.yml`

```yml
package:
  individually: true
  exclude:
    - "**/*"
  include:
    - functions/**/*

functions:
  handler1:
    handler: functions/handler1/index.hello
    package:
      include:
        - functions/handler1/index.js
        - node_modules/**/*
```

the wrapped function `_lumigo/handler1.js` would not be in the packaged zip file
