### ISSUE TITLE
Cannot find module '@lumigo/tracer'

### ISSUE THREAD

**Issue by samuelcastro** [lumigo-io/serverless-lumigo-plugin#108]
Hello, for some reason I'm getting this error in my lambdas:

```
UserLambdaValidationException: PostConfirmation failed with error Error: Cannot find module '@lumigo/tracer'
    Require stack:
    - /var/task/_lumigo/confirmUserSignup.js
    - /var/runtime/UserFunction.js
    - /var/runtime/Runtime.js
    - /var/runtime/index.js.
```

My serverless.yml

```yml
custom
   lumigo:
      token: ${ssm:/${self:custom.stage}/lumigo-token~true}
      skipInstallNodeTracer: true
      nodePackageManager: yarn
```

package.json

```json
"devDependencies": {
    "serverless-lumigo": "^1.13.3",
...
},
"dependencies": {
    "@lumigo/tracer": "^1.71.4",
...
}
```

I wonder if this issue was caused by the fact that I initially integrated lumigo manually, and now I'm integrating it via the the serverless.yml file.

I tried to removed my current project on Lumigo to integrate it via serverless-lumigo but I can't find an option to delete my current project on Lumigo.

Do you have any idea what's happening?
