### ISSUE TITLE
Global Enable Flag

### ISSUE THREAD

**Issue by chrismrgn** [lumigo-io/serverless-lumigo-plugin#74]
Request to add a global flag to enable / disable Lumigo, so that in temporary / development environments it can be dynamically disabled based on deployment stage.

Example:
```
custom:
  lumigo:
    token: <YOUR TOKEN GOES HERE>
    skipInstallNodeTracer: true # defaults to false
    enabled: false
```
