### ISSUE TITLE
when different functions have the same filename, the last one wins

### ISSUE THREAD

**Issue by theburningmonk** [lumigo-io/serverless-lumigo-plugin#8]
e.g. given this `serverless.yml`

```yml
functions:
  handler1:
    handler: functions/handler1/index.hello

  handler2:
    handler: functions/handler2/index.hello
```

because both have a file called `index.js` the plugin generates only one wrapped function `_lumigo/index.js`
